hash_validator: dictionary.o hash_validator.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow -o hash_validator hash_validator.c dictionary.o -lm
